# k8s/proxy/proxy-deployment.yaml

apiVersion: apps/v1
kind: Deployment

metadata:
  name: prompt-me-proxy
  namespace: prompt-core

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prompt-me-proxy

  template:
    metadata:
      labels:
        app: prompt-me-proxy

    spec:
      containers:
        - name: prompt-me-proxy

          image: nishadevi333/prompt-me-proxy:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "250m"
              memory: "512Mi"

          envFrom:
            - configMapRef:
                name: prompt-shared-config

          env:
            - name: REDIS_URL
              value: "redis://redis-0.redis.prompt-core.svc.cluster.local:6379"

            - name: PORT
              value: "80"

---
apiVersion: v1
kind: Service

metadata:
  name: prompt-me-proxy
  namespace: prompt-core
spec:
  selector: 
    app: prompt-me-proxy
  ports: 
    - port: 80
      targetPort: 80